### ISSUE TITLE
removing all dependencies crashes this plugin

### ISSUE THREAD

**Issue by orta** [orta/danger-plugin-yarn#8]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `/app/danger-0.e1gszunuyuayzcjmqnv29be29.ts`.
  </td>
    </tr>
  </tbody>
</table>

## Error TypeError
```
Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at Object.exports.checkForTypesInDeps.packageDiff [as checkForTypesInDeps] (/app/node_modules/danger-plugin-yarn/dist/index.js:180:57)
    at Object.<anonymous> (/app/node_modules/danger-plugin-yarn/dist/index.js:197:17)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/danger-plugin-yarn/dist/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
### Dangerfile
```
------------------------------------------------------------^
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by orta** [comment]
https://github.com/artsy/artsy-danger/pull/17

**Comment by hawkrives** [comment]
Closed by https://github.com/orta/danger-plugin-yarn/pull/11?

**Comment by orta** [comment]
Yep, think so

**Comment by hawkrives** [comment]
👍
